import { StyleSheet } from "react-native";
import { colors } from "../Themes/Colors";
import { horizontalScale, moderateScale, verticalScale } from "../Themes/Metrics";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.lightPink,
    },
    bgImg:{
        flex:1,
        justifyContent:"center"
    },
    mainView:{
        flex:1,
        padding:moderateScale(15),
    },
    topView:{
        flexDirection:"row",
        justifyContent:"space-between",
        paddingBottom:verticalScale(20),
    },
    titleText:{
        fontSize:moderateScale(19),
        fontWeight:"600",
    },
    searchView:{
        flexDirection:"row",
        gap:8,
        paddingBottom:verticalScale(10),
    },
    searchBar:{
        flex:1,
        borderWidth:2,
        padding:moderateScale(10),
        borderColor:colors.lightGrey,
        borderRadius:moderateScale(10),
        fontSize:moderateScale(16),
        backgroundColor:colors.white
    },
    addBtn:{
        paddingHorizontal:horizontalScale(20),
        borderRadius:moderateScale(9),
        backgroundColor:colors.Primary,
        justifyContent:"center",
    },
    addText:{
        color:colors.white,
        fontSize:moderateScale(16),
        fontWeight:"600",
    },
    trioBtnView:{
        flexDirection:"row",
        gap:5,
        justifyContent:"space-between",
        marginVertical:verticalScale(10),
    },
    button:{
        flex:1,
        paddingVertical:verticalScale(10),
        borderRadius:moderateScale(9),
        alignItems:"center",
    },
    selectionText:{
        fontSize:moderateScale(14),
        fontWeight:"500",
    },
    selectedBtn:{
        backgroundColor:colors.Primary,  
    },
    selectedText:{
        color:colors.white,
    },
    diableBtn:{
        backgroundColor:colors.lightPurple,
    },
    disableText:{
        color:colors.Primary,    
    },
    listView:{
        padding:moderateScale(20),
        marginVertical:verticalScale(10),
        backgroundColor:colors.offWhite,
        borderRadius:moderateScale(15),
        flexDirection:"row",
        justifyContent:"space-between",
    },
    dropShadow:{
        shadowColor:colors.shadow,
        shadowOffset:{height:4,width:0},
        shadowOpacity:32,
    },
    infoView:{
        justifyContent:"space-between",
    },
    infoText:{
        fontSize:moderateScale(14),
        fontWeight:"500",
    },
    logoIconView:{
        paddingBottom:verticalScale(10)
    },
    iconView:{
        borderRadius:moderateScale(7),
        marginHorizontal:horizontalScale(14),
    },
    statusIcon:{
        margin:moderateScale(6)
    },
    activeIcon:{
        backgroundColor:colors.lightPurple,
    },
    completeIcon:{
        backgroundColor:colors.babyPink,
    },
    priorityView:{
        alignItems:"center",
        borderRadius:moderateScale(7),
        paddingVertical:verticalScale(2),
        paddingHorizontal:horizontalScale(7)
    },
    priorityText:{
        fontSize:moderateScale(11),
    },
    highText:{
        color:colors.Primary,
    },
    mediumText:{
        color:colors.orange,
    },
    lowText:{
        color:colors.primaryBlue,
    },
    highBg:{
        backgroundColor:colors.lightPurple,
    },
    mediumBg:{
        backgroundColor:colors.lightOrange,
    },
    lowBg:{
        backgroundColor:colors.lightPrimaryBlue
    },
    dateView:{
        flexDirection:"row"
    },
    dateText:{
        alignSelf:"center",
        color:colors.Primary,
    },
});