import { StyleSheet } from "react-native";
import { colors } from "../Themes/Colors";
import { horizontalScale, moderateScale, verticalScale } from "../Themes/Metrics";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:colors.lightPink,
    },
    bgImg:{
        flex:1,
        // alignItems: 'center',
        justifyContent:"center"
    },
    mainView:{
        flex:1,
        padding:moderateScale(15),
    },
    topView:{
        flexDirection:"row",
        justifyContent:"space-between",
        paddingBottom:verticalScale(20),
    },
    titleText:{
        fontSize:moderateScale(19),
        fontWeight:"600",
    },
    searchView:{
        flexDirection:"row",
        gap:8,
        paddingBottom:verticalScale(10),
    },
    searchBar:{
        flex:1,
        borderWidth:2,
        padding:moderateScale(10),
        borderColor:colors.lightGrey,
        borderRadius:moderateScale(10),
        fontSize:moderateScale(16),
        backgroundColor:colors.white
    },
    addBtn:{
        paddingHorizontal:horizontalScale(20),
        borderRadius:moderateScale(9),
        backgroundColor:colors.Primary,
        justifyContent:"center",
    },
    addText:{
        color:colors.white,
        fontSize:moderateScale(16),
        fontWeight:"600",
    },
    trioBtnView:{
        flexDirection:"row",
        gap:5,
        justifyContent:"space-between",
        marginVertical:verticalScale(10),
    },
    button:{
        flex:1,
        paddingVertical:verticalScale(10),
        borderRadius:moderateScale(9),
        alignItems:"center",
    },
    selectionText:{
        fontSize:moderateScale(16),
        fontWeight:"600",
    },
    selectedBtn:{
        backgroundColor:colors.Primary,  
    },
    selectedText:{
        color:colors.white,
    },
    diableBtn:{
        backgroundColor:colors.lightPurple,
    },
    disableText:{
        color:colors.Primary,    
    },
    listView:{
        padding:moderateScale(30),
        marginVertical:verticalScale(10),
        backgroundColor:colors.offWhite,
        borderRadius:moderateScale(15),
    },
    dropShadow:{
        shadowColor:colors.shadow,
        shadowOffset:{height:4,width:0},
        shadowOpacity:32,
    }
});